// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtAa17tFKvT8BI5NsnNz_DZS7lzncbt8',
    appId: '1:798267470755:web:a9b58cf86e85d801466016',
    messagingSenderId: '798267470755',
    projectId: 'gharounda-c8678',
    authDomain: 'gharounda-c8678.firebaseapp.com',
    storageBucket: 'gharounda-c8678.appspot.com',
    measurementId: 'G-VCBNVJFT3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Cq5vMLWr9ADMGY_shWWVutJlFBc5QmU',
    appId: '1:798267470755:android:7c829cf86d804f98466016',
    messagingSenderId: '798267470755',
    projectId: 'gharounda-c8678',
    storageBucket: 'gharounda-c8678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-uW2lRj1fjLj9TalJxv_x8i-q-m2S0c',
    appId: '1:798267470755:ios:71a915a91dd71de3466016',
    messagingSenderId: '798267470755',
    projectId: 'gharounda-c8678',
    storageBucket: 'gharounda-c8678.appspot.com',
    iosClientId: '798267470755-l5657m35m0dl3pb525jlkk2qvmp0m032.apps.googleusercontent.com',
    iosBundleId: 'com.classima.lagosabuja',
  );
}
